# Generated by Django 3.1.2 on 2020-10-16 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('payment_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'payment Method',
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField(null=True)),
                ('product_description', models.CharField(max_length=50)),
                ('unit_price', models.FloatField(null=True)),
                ('quantity', models.FloatField(null=True)),
                ('total_price', models.FloatField(null=True)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.client')),
                ('payment_method_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.paymentmethod')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
