# Generated by Django 3.1.1 on 2020-10-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20201010_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='ticket_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='unit_price',
            field=models.FloatField(null=True),
        ),
    ]
