# Generated by Django 3.1.2 on 2020-10-16 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('barcode', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'categorie',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Kilate',
            fields=[
                ('kilate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='UnitMeasurement',
            fields=[
                ('unit_measurement_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'units Measurement',
                'db_table': 'units_measurements',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('direction', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField(null=True)),
                ('barcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.barcode')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.category')),
                ('kilate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.kilate')),
                ('unit_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.unitmeasurement')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='barcode',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.category'),
        ),
        migrations.AddField(
            model_name='barcode',
            name='kilate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.kilate'),
        ),
    ]
