# Generated by Django 3.1.1 on 2020-10-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='unitmeasurement',
            table='units_measurements',
        ),
    ]
