# Generated by Django 3.1.2 on 2020-10-18 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='unitmeasurement',
            options={'verbose_name': 'unit Measurement', 'verbose_name_plural': 'units Measurements'},
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='direction',
            new_name='address',
        ),
    ]
