# Generated by Django 3.1.1 on 2020-10-10 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_auto_20201010_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categories'},
        ),
    ]
