# Generated by Django 3.1.1 on 2020-10-10 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_auto_20201010_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categorie'},
        ),
    ]
