# Generated by Django 3.1.2 on 2020-10-21 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_auto_20201021_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.barcode'),
        ),
    ]
