# Generated by Django 3.1.1 on 2020-10-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0004_auto_20201010_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitmeasurement',
            options={'verbose_name': 'unit measurement'},
        ),
    ]
