# Generated by Django 3.1.1 on 2020-10-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0005_auto_20201010_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitmeasurement',
            options={'verbose_name': 'units Measurement'},
        ),
    ]
