# Generated by Django 3.1.1 on 2020-10-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0006_auto_20201010_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.FloatField(null=True),
        ),
    ]
