# Generated by Django 3.1.2 on 2020-10-15 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0008_auto_20201011_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
    ]
