# Generated by Django 3.1.2 on 2020-10-15 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0009_remove_product_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('barcode_id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.BigIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.category')),
                ('kilate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.kilate')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.barcode'),
        ),
    ]
