# Generated by Django 3.1.2 on 2020-10-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0010_auto_20201015_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='barcode',
            field=models.IntegerField(),
        ),
    ]
